main_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pokemon/', views.pokemon_index, name='index'),
    path('pokemon/<int:poke_id>/', views.pokemon_detail, name='detail'),
    path('pokemon/create/', views.PokemonCreate.as_view(), name='pokemon_create'),

    path('pokemon/<int:pk>/update/',
         views.PokemonUpdate.as_view(), name='pokemon_update'),

    path('pokemon/<int:pk>/delete/',
         views.PokemonDelete.as_view(), name='pokemon_delete'),

    path('pokemon/<int:poke_id>/add_ability/',
         views.add_ability, name='add_ability'),

    path('items/', views.ItemList.as_view(), name='items_index'),

    path('items/<int:pk>/', views.ItemDetail.as_view(), name='items_detail'),

    path('items/create/', views.ItemCreate.as_view(), name='items_create'),

    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='items_update'),

    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='items_delete'),

    path('pokemon/<int:poke_id>/assoc_item/<int:item_id>/',
         views.assoc_item, name='assoc_item'),

    path('accounts/signup/', views.signup, name='signup'),
]

pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main_app.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.urls import reverse
import random
from django.contrib.auth.models import User

# Create your models here.
ABILITIES = (
    ('A', 'Growl'),
    ('B', 'Take Down'),
    ('C', 'Tackle'),
    ('D', 'Rest'),
    ('E', 'Protect'),
    ('F', 'Special Attack'),
)


class Item(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    description = models.TextField(
        max_length=250,
        default='none'
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('items_detail', kwargs={'pk': self.id})


class Pokemon(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100, default='none')
    hp = models.IntegerField()
    attack = models.IntegerField()
    defense = models.IntegerField()
    sp_attack = models.IntegerField()
    sp_defense = models.IntegerField()
    speed = models.IntegerField()
    items = models.ManyToManyField(Item)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to='images/')

    def __str__(self):
        return self.name

    def save(self):
        self.type = self.type.lower()
        return super(Pokemon, self).save()

    def average(self):
        sum = (self.hp + self.attack + self.defense +
               self.sp_attack + self.sp_defense + self.speed) / 6
        average = round(sum)
        return average

    def total(self):
        total = self.hp + self.attack + self.defense + \
            self.sp_attack + self.sp_defense + self.speed
        return total

    def get_absolute_url(self):
        return reverse('detail', kwargs={'poke_id': self.id})

    def upper(self):
        upper = self.user.upper()
        return upper

    class Meta:
        ordering = ['name']


class Ability(models.Model):
    ability = models.CharField(
        max_length=1,
        choices=ABILITIES,
        default=ABILITIES[0][0]
    )

    poke = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_ability_display()}'

    def power(self):
        power = self.poke.total()
        rand_num = random.randint(50, power)
        return rand_num

    def accuracy(self):
        rand_num = random.randint(10, 100)
        return rand_num

main_app/forms.py
from django.forms import ModelForm
from .models import Ability


class AbillityForm(ModelForm):
    class Meta:
        model = Ability
        fields = ['ability']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Pokemon, Item
from .forms import AbillityForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class PokemonCreate(LoginRequiredMixin, CreateView):
    model = Pokemon
    fields = ['name', 'type', 'hp', 'attack', 'defense',
              'sp_attack', 'sp_defense', 'speed', 'image']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PokemonUpdate(LoginRequiredMixin, UpdateView):
    model = Pokemon
    fields = ['name', 'type', 'hp', 'attack', 'defense',
              'sp_attack', 'sp_defense', 'speed', 'image']


class PokemonDelete(LoginRequiredMixin, DeleteView):
    model = Pokemon
    success_url = '/pokemon/'


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def pokemon_index(request):
    pokemon = Pokemon.objects.all()
    return render(request, 'pokemon/index.html', {'pokemon': pokemon})


@login_required
def pokemon_detail(request, poke_id):
    poke = Pokemon.objects.get(id=poke_id)
    items_poke_doesnt_have = Item.objects.exclude(
        id__in=poke.items.all().values_list('id'))
    ability_form = AbillityForm()
    return render(request, 'pokemon/detail.html', {'poke': poke,
                                                   'ability_form': ability_form, 'items': items_poke_doesnt_have})


@login_required
def add_ability(request, poke_id):
    form = AbillityForm(request.POST)
    if form.is_valid():
        new_ability = form.save(commit=False)
        new_ability.poke_id = poke_id
        new_ability.save()
    return redirect('detail', poke_id=poke_id)


class ItemList(ListView):
    model = Item


class ItemDetail(LoginRequiredMixin, DetailView):
    model = Item


class ItemCreate(LoginRequiredMixin, CreateView):
    model = Item
    fields = '__all__'


class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = '__all__'


class ItemDelete(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = '/items/'


@login_required
def assoc_item(request, poke_id, item_id):
    Pokemon.objects.get(id=poke_id).items.add(item_id)
    return redirect('detail', poke_id=poke_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - Try Again!'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Collector</h1>
<hr />
<h3>The Ultimate Pokemon Collector</h3>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="cache-control" content="no-cache" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'css/style.css' %}">
    <title>Pokemon Collector</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
          <a id='nav-text' class="navbar-brand" href="/">Pokemon Collector</a>
          <button id='nav-btn' class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a id='text' class="nav-link active" aria-current="page" href="/">Home</a>
              {% if user.is_authenticated %}
              <a id='text' class="nav-link" href="{% url 'items_index' %}">Items </a>
              <a id='text' class="nav-link" href="{% url 'items_create' %}"> Add An Item </a>
              <a id='text' class="nav-link" href="{% url 'pokemon_create' %}">Add A Pokemon </a>
              <a id='text' class="nav-link" href="{% url 'index' %}">View Pokemon</a>
              <a id='text' class="nav-link" href="{% url 'logout' %}">Log Out</a>
              {% else %}
              <a id='text' class="nav-link" href="{% url 'index' %}">View Pokemon</a>
              <a id='text' class="nav-link" href="{% url 'items_index' %}">Items </a>
              <a id='text' class="nav-link" href="{% url 'login' %}">Log In</a>
              <a id='text' class="nav-link" href="{% url 'signup' %}">Sign Up</a>
              {% endif %}

            </div>
          </div>
        </div>
      </nav>
      <main class='container'>
          {% block content %}
          {% endblock %}
      </main>
    
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Collector Home</h1>
<hr />
<h3>The Ultimate Pokemon Collector</h3>

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Item</h1>

    <h4>Are you sure you want to delete {{ object.name }}?</h4>

    <form action='' method='POST'>
        {% csrf_token %}
        <input type='submit' value='DELETE' class='btn btn-primary'>
        <a class='btn btn-primary' href="{% url 'items_detail' object.id%}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{item.name}} Details</h1>
<div class='container-card'>
    <div class="card" style="width: 16rem;">
        <a href=""><img src="{{ item.image.url }}" class="card-img-top"></a>
        <div class="card-body">
          <h5 class="card-title">{{ item.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
    
          <li class="list-group-item"> {{ item.description }}</li>
            </ul>
        <a class="btn btn-primary" href="{% url 'items_update' item.id %}" role="button">Edit</a>
        <a class="btn btn-primary" href="{% url 'items_delete' item.id %}" role="button">Delete</a>    
      </div>
    </div>


{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %} 
    <h1>Edit {{ object.name }}</h1>
{% else %} 
    <h1>Add New Item</h1>
{% endif %}
<form action="" method="post" enctype='multipart/form-data' class='poke-form'> 
    {% csrf_token %}
    <table id='table' class="table table-striped">

        {{ form.as_table }}
    </table>
    <input type='submit' value="Submit" class='btn btn-primary'>
</form>


{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %}
{% block content %}

<h1> SHOWING ALL ITEMS</h1>
<div class='container-card'>
{% for item in item_list %}
<div class="card" style="width: 17rem;">
    <a href="{% url 'items_detail' item.id %}"><img src='{{item.image.url}}' class="card-img-top"></a>
    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">

      <li class="list-group-item"> {{ item.description }}</li>

    </ul>

  </div>
  {% endfor %}
</div>


{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Pokemon</h1>

    <h4>Are you sure you want to delete {{ object.name }}?</h4>

    <form action='' method='POST'>
        {% csrf_token %}
        <input type='submit' value='DELETE' class='btn btn-primary'>
        <a class='btn btn-primary' href="{% url 'detail' object.id%}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}
{% block content%}


{% if object %} 
    <h1>Edit {{ object.name }}</h1>
{% else %} 
    <h1>Add Pokemon</h1>
{% endif %}
<form action="" method="post" enctype='multipart/form-data' class='poke-form'> 
    {% csrf_token %}
    <table id='table' class="table table-striped">

        {{ form.as_table }}
    </table>
    <input type='submit' value="Submit" class='btn btn-primary'>
</form>



{% endblock%}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}

<h1> SHOWING {{ poke.name }} DETAILS</h1>

<!--MAIN DIV CONTAINER-->

<div class='container-card'>

  <!-- MAIN POKEMON CARD-->

  <div class="card" style="width: 18rem;">
    <img src="{{ poke.image.url }}" class="card-img-top" alt="...">
    
    <div class="card-body">
      <h5 class="card-title">{{ poke.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
      {% if poke.type == 'water' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-water'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'bug' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-bug'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'flying' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-flying'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'poison' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-poison'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'electric' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-electric'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'grass' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-grass'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'fire' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-fire'>{{ poke.type }}</span></li>
      {% endif %}
      <li class="list-group-item">HP: {{ poke.hp }}</li>
      <li class="list-group-item">ATTACK: {{ poke.attack }}</li>
      <li class="list-group-item">DEFENSE: {{ poke.defense }}</li>
      <li class="list-group-item">SP ATTACK: {{ poke.sp_attack }}</li>
      <li class="list-group-item">SP DEFENSE: {{ poke.sp_defense }}</li>
      <li class="list-group-item">SPEED: {{ poke.speed }}</li>
      <li class="list-group-item" id='bolder'>TOTAL: {{ poke.total }}</li>
      <li class="list-group-item" id='bolder'>AVERAGE: {{ poke.average }}</li>
    </ul>
      <a class="btn btn-primary" href="{% url 'pokemon_update' poke.id %}" role="button">Edit</a>
      <a class="btn btn-primary" href="{% url 'pokemon_delete' poke.id %}" role="button">Delete</a>
  </div>

  <!-- ADD ABILITY FORM-->

  
  
  <!-- ABILITY DISPLAY TABLE-->

    <table id='table' class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ABILITY</th>
          <th scope="col">POWER</th>
          <th scope="col">ACCURACY</th>
        </tr>
      </thead>
      <tbody>
        {% for ability in poke.ability_set.all %}
        <tr>
          <td>{{ability.get_ability_display}}</td>
          <td>{{ability.power}}</td>
          <td>{{ability.accuracy}}%</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>    
    <form action="{% url 'add_ability' poke.id %}"method="post">
      {% csrf_token %}
      {{ ability_form.as_p }}
      <input type='submit' class='btn btn-primary' value='Add Ability'>
    </form>
   


</div>
    <!-- POKE ITEMS OWNED-->
    
    <h3> Items for {{poke.name}}: </h3>
    
    <div class='container-card'>
    {% if poke.items.count %}
      {% for item in poke.items.all %}

  <div class="card" style="width: 17rem;">
    <img src="{{ item.image.url }}" class="card-img-top" alt="pokeball">

    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text">{{ item.description }}</p>
    </div>

  </div>
      {% endfor %}
    
    {% else %}
  <h3>Currently {{poke.name }} has no items</h3>
    {% endif %}
  </div>

  <!-- POKE ITEMS AVAILABLE TO ADD-->

  {% if items.count %}
  <h3> Add an Item:</h3>
  <div class='container-card'>
    {% for item in items.all %}
    
  <div class="card" style="width: 17rem;">
    <img src="{{ item.image.url }}" class="card-img-top" alt="pokeball">

    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text">{{ item.description }}</p>
    </div>

    <form action="{% url 'assoc_item' poke.id item.id %}" method='POST'>
      {% csrf_token %}
      <button type='submit' class='btn btn-primary'>Add</button>
    </form>

  </div>
      {% endfor %}

  {% else %}
    <h3>{{ poke.name }} Has every item</h3>
  {% endif %}

  <!--CLOSING DIV MAIN CONTAINER-->
</div>
{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}

<h1> SHOWING ALL POKEMON</h1>
<div class='container-card'>
{% for poke in pokemon %}
<div class="card carousel-item active" style="width: 18rem;">
    <a href="{% url 'detail' poke.id %}"><img src="{{ poke.image.url }}" class="card-img-top" alt="..."></a>
    <div class="card-body">
      <h5 class="card-title">{{ poke.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
      {% if poke.type == 'water' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-water'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'bug' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-bug'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'flying' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-flying'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'poison' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-poison'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'electric' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-electric'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'grass' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-grass'>{{ poke.type }}</span></li>
      {% endif %}
      {% if poke.type == 'fire' %}
      <li class="list-group-item">TYPE: <span class='poke-type poke-type-fire'>{{ poke.type }}</span></li>
      {% endif %}
      <li class="list-group-item">HP: {{ poke.hp }}</li>
      <li class="list-group-item">ATTACK: {{ poke.attack }}</li>
      <li class="list-group-item">DEFENSE: {{ poke.defense }}</li>
      <li class="list-group-item">SP ATTACK: {{ poke.sp_attack }}</li>
      <li class="list-group-item">SP DEFENSE: {{ poke.sp_defense }}</li>
      <li class="list-group-item">SPEED: {{ poke.speed }}</li>
      <li class="list-group-item" id='bolder'>TOTAL: {{ poke.total }}</li>
      <li class="list-group-item" id='bolder'>AVERAGE: {{ poke.average }}</li>
    </ul>

  </div>
  {% endfor %}
</div>
{% endblock %}